name: text_analyzer
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_ml_kit: ^0.14.0
  google_mlkit_text_recognition: ^0.6.0
  image_picker: ^0.8.4+4
  flutter_provider: ^2.1.0
  http: ^0.13.5
  flutter_dotenv: ^5.0.2
  provider: ^6.0.5
  page_view_dot_indicator: ^2.1.0
  kakao_flutter_sdk: ^1.4.2
  url_launcher: ^6.1.11
  path_provider: ^2.0.15
  google_mlkit_barcode_scanning: ^0.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/image_background.png
    - assets/images/capture.png
    - assets/images/choose_photo.png
    - assets/images/loading1.png
    - assets/images/result1.png
    - assets/images/load_complete1.png
    - assets/images/resultDogs/bishon2.png
    - assets/images/resultDogs/chew2.png
    - assets/images/resultDogs/chiwawa2.png
    - assets/images/resultDogs/coly2.png
    - assets/images/resultDogs/dalmasian2.png
    - assets/images/resultDogs/germanshapered2.png
    - assets/images/resultDogs/hound2.png
    - assets/images/resultDogs/maltize2.png
    - assets/images/resultDogs/pomeranian2.png
    - assets/images/resultDogs/poodle2.png
    - assets/images/resultDogs/ristriber.png
    - assets/images/resultDogs/york2.png
    - assets/images/utils/graphic_kakao.png
    - assets/images/utils/graphic_instagram.png
    - assets/images/utils/graphic_facebook.png
    - assets/images/resultDogsWithBody/bis.png
    - assets/images/resultDogsWithBody/chew.png
    - assets/images/resultDogsWithBody/chi.png
    - assets/images/resultDogsWithBody/col.png
    - assets/images/resultDogsWithBody/dalma.png
    - assets/images/resultDogsWithBody/houn.png
    - assets/images/resultDogsWithBody/lit.png
    - assets/images/resultDogsWithBody/mal.png
    - assets/images/resultDogsWithBody/pome.png
    - assets/images/resultDogsWithBody/pood.png
    - assets/images/resultDogsWithBody/shap.png
    - assets/images/resultDogsWithBody/york.png
    - .env
