name: text_analyzer
description: A new Flutter project.
publish_to: 'none'
version: 5.0.2+7

environment:
  sdk: '>=2.19.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.13.0
  google_ml_kit: ^0.14.0
  google_mlkit_text_recognition: ^0.6.0
  image_picker: ^0.8.4+4
  flutter_provider: ^2.1.0
  http: ^0.13.5
  flutter_dotenv: ^5.0.2
  provider: ^6.0.5
  page_view_dot_indicator: ^2.1.0
  kakao_flutter_sdk: ^1.4.2
  url_launcher: ^6.1.11
  path_provider: ^2.0.15
  google_mlkit_barcode_scanning: ^0.6.0
  flutter_share: ^2.0.0
  firebase: ^9.0.3
  cloud_firestore: ^4.7.1
  firebase_storage: ^11.2.1
  social_share: ^2.3.1
  google_mobile_ads: ^3.0.0
  facebook_audience_network: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/image_background.png
    - assets/images/capture.png
    - assets/images/choose_photo.png
    - assets/images/loading1.png
    - assets/images/result1.png
    - assets/images/load_complete1.png
    - assets/images/resultDogs/bishon2.png
    - assets/images/resultDogs/chew2.png
    - assets/images/resultDogs/chiwawa2.png
    - assets/images/resultDogs/coly2.png
    - assets/images/resultDogs/dalmasian2.png
    - assets/images/resultDogs/germanshapered2.png
    - assets/images/resultDogs/hound2.png
    - assets/images/resultDogs/maltize2.png
    - assets/images/resultDogs/pomeranian2.png
    - assets/images/resultDogs/poodle2.png
    - assets/images/resultDogs/ristriber.png
    - assets/images/resultDogs/york2.png
    - assets/images/utils/graphic_kakao.png
    - assets/images/utils/graphic_instagram.png
    - assets/images/utils/graphic_facebook.png
    - assets/images/resultDogsWithBody/bis.png
    - assets/images/resultDogsWithBody/chew.png
    - assets/images/resultDogsWithBody/chi.png
    - assets/images/resultDogsWithBody/col.png
    - assets/images/resultDogsWithBody/dalma.png
    - assets/images/resultDogsWithBody/houn.png
    - assets/images/resultDogsWithBody/lit.png
    - assets/images/resultDogsWithBody/mal.png
    - assets/images/resultDogsWithBody/pome.png
    - assets/images/resultDogsWithBody/pood.png
    - assets/images/resultDogsWithBody/shap.png
    - assets/images/resultDogsWithBody/york.png
    - assets/images/illustrate/il_aiwork.png
    - assets/images/illustrate/il_bis.png
    - assets/images/illustrate/il_bod.png
    - assets/images/illustrate/il_che.png
    - assets/images/illustrate/il_chi.png
    - assets/images/illustrate/il_dal.png
    - assets/images/illustrate/il_hou.png
    - assets/images/illustrate/il_lit.png
    - assets/images/illustrate/il_mal.png
    - assets/images/illustrate/il_pod.png
    - assets/images/illustrate/il_pom.png
    - assets/images/illustrate/il_sha.png
    - assets/images/illustrate/il_yor.png
    - assets/images/utils/dog_step.gif
    - .env
